name: CI/CD Pipeline with Security Testing

on:
  push:
    branches:
      - master  # Déclenche le pipeline pour les commits dans la branche "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifier d'abord si un conteneur Juice Shop existe déjà
    - name: Check if Juice Shop is already running
      id: check-container
      run: |
        if docker ps --filter "name=juice-shop" --filter "status=running" | grep juice-shop; then
          echo "running=true" >> $GITHUB_ENV
        else
          echo "running=false" >> $GITHUB_ENV
        fi

    # 2. Arrêter et supprimer l'ancien conteneur si nécessaire
    - name: Clean up existing container
      if: env.running == 'true'
      run: |
        docker stop juice-shop
        docker rm juice-shop

    # 3. Lancer un nouveau conteneur
    - name: Run Juice Shop container
      if: env.running == 'false'
      run: |
        docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop:latest

    # 4. Attendre que Juice Shop démarre
    - name: Wait for Juice Shop to start
      run: |
        for i in {1..30}; do
          if curl -I http://localhost:3000 2>/dev/null | grep "200 OK"; then
            echo "Juice Shop is ready!";
            break;
          fi;
          echo "Waiting for Juice Shop...";
          sleep 2;
        done

    # 5. Tester l'application pour vérifier qu'elle fonctionne
    - name: Test application
      run: |
        curl -I http://localhost:3000 | grep "200 OK"

    # 6. Liste des conteneurs actifs pour débogage
    - name: List running containers
      run: docker ps

  # SAST (Static Application Security Testing)
  sast:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript  # Utilisez javascript ou autre si nécessaire

    - name: Analyze with CodeQL
      uses: github/codeql-action/analyze@v2
      continue-on-error: true  # Laisse le pipeline continuer même si des erreurs de sécurité sont trouvées

  # SCA (Software Composition Analysis) - Dépendances
  sca:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Télécharger la dernière version de Dependency-Check à partir de GitHub
    - name: Install Dependency-Check CLI
      run: |
        # Cloner le dépôt Dependency-Check
        git clone https://github.com/jeremylong/DependencyCheck.git
        cd DependencyCheck
        VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
        echo "Downloading Dependency-Check version $VERSION"
        curl -Ls "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip
        unzip dependency-check.zip -d dependency-check
        chmod +x dependency-check/bin/dependency-check.sh

    # Exécuter l'analyse de dépendance sur le projet
    - name: Run SCA (Dependency Check)
      run: |
        ./dependency-check/bin/dependency-check.sh --project OWASP-Juice-Shop --scan . --out ./dependency-check-report

    # Télécharger le rapport de Dependency-Check
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ./dependency-check-report

  # DAST (Dynamic Application Security Testing)
  dast:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    # Installation de ZAP via Snap
    - name: Install OWASP ZAP via Snap
      run: |
        sudo apt update
        sudo snap install zaproxy

    # Lancer OWASP ZAP en mode daemon
    - name: Start OWASP ZAP in daemon mode
      run: |
        zaproxy -daemon -host 0.0.0.0 -port 8080
        sleep 10  # Attendre que ZAP démarre correctement

    # Exécuter un scan rapide avec ZAP
    - name: Run OWASP ZAP Scan
      run: |
        zap-cli quick-scan --self-contained --start-options "-daemon -host 0.0.0.0 -port 8080" --url http://localhost:3000

    # Générer le rapport ZAP en format HTML
    - name: Generate ZAP HTML Report
      run: |
        zap-cli report -o zap-report.html -f html
        cat zap-report.html

    # Télécharger le rapport ZAP
    - name: Upload OWASP ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap-report.html
