name: CI/CD Pipeline avec Reporting Complet de Sécurité

on:
  push:
    branches:
      - master

env:
  JUICE_SHOP_IMAGE: bkimminich/juice-shop:latest
  REPORTS_DIR: ${{ github.workspace }}/security-reports

jobs:
  prepare-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Créer le répertoire de rapports
        run: mkdir -p ${{ env.REPORTS_DIR }}

  deploy-and-scan:
    needs: prepare-reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      # Déploiement de Juice Shop
      - name: Déployer Juice Shop
        run: |
          docker pull ${{ env.JUICE_SHOP_IMAGE }}
          docker run -d -p 3000:3000 --name juice-shop ${{ env.JUICE_SHOP_IMAGE }}

      # SAST avec CodeQL
      - name: Analyse de Sécurité Statique (CodeQL)
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript
      
      - name: Exécuter Analyse CodeQL
        uses: github/codeql-action/analyze@v2
        with:
          output: ${{ env.REPORTS_DIR }}/codeql-report.sarif

      # Scan de Dépendances
      - name: Vérification des Dépendances
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'OWASP Juice Shop'
          path: '.'
          format: 'HTML, JSON, XML'
          outputDirectory: ${{ env.REPORTS_DIR }}

      # DAST avec OWASP ZAP
      - name: Scan de Sécurité Dynamique (OWASP ZAP)
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-a -j -m 5 -T 5'
          
      # Générer un rapport consolidé
      - name: Créer Rapport Consolidé
        run: |
          echo "# Rapport Consolidé de Sécurité" > ${{ env.REPORTS_DIR }}/security-report.md
          
          echo "## 📋 Résumé Exécutif" >> ${{ env.REPORTS_DIR }}/security-report.md
          echo "- **Date du Scan:** $(date '+%Y-%m-%d %H:%M:%S')" >> ${{ env.REPORTS_DIR }}/security-report.md
          echo "- **Référentiel:** ${{ github.repository }}" >> ${{ env.REPORTS_DIR }}/security-report.md
          echo "- **Commit:** ${{ github.sha }}" >> ${{ env.REPORTS_DIR }}/security-report.md
          
          echo "## 🔍 Résultats des Analyses" >> ${{ env.REPORTS_DIR }}/security-report.md
          
          # Résultats CodeQL
          echo "### 🛡️ Analyse Statique (CodeQL)" >> ${{ env.REPORTS_DIR }}/security-report.md
          if [ -f "${{ env.REPORTS_DIR }}/codeql-report.sarif" ]; then
            echo "- Rapport SARIF généré" >> ${{ env.REPORTS_DIR }}/security-report.md
          else
            echo "- Aucun problème majeur détecté" >> ${{ env.REPORTS_DIR }}/security-report.md
          fi
          
          # Résultats Dépendances
          echo "### 📦 Analyse des Dépendances" >> ${{ env.REPORTS_DIR }}/security-report.md
          if ls ${{ env.REPORTS_DIR }}/dependency-check-report.* 1> /dev/null 2>&1; then
            echo "- Rapport de dépendances généré" >> ${{ env.REPORTS_DIR }}/security-report.md
          else
            echo "- Aucune vulnérabilité critique dans les dépendances" >> ${{ env.REPORTS_DIR }}/security-report.md
          fi
          
          # Résultats ZAP
          echo "### 🌐 Test de Sécurité Dynamique (OWASP ZAP)" >> ${{ env.REPORTS_DIR }}/security-report.md
          echo "- Scan de base effectué sur l'application" >> ${{ env.REPORTS_DIR }}/security-report.md

  generate-report-artifact:
    needs: deploy-and-scan
    runs-on: ubuntu-latest
    steps:
      # Upload des rapports
      - name: Sauvegarder les Rapports de Sécurité
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: ${{ env.REPORTS_DIR }}

  # Étape de notification optionnelle
  notify:
    needs: generate-report-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer Notification Slack (Exemple)
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 🚨 Problèmes de sécurité détectés dans le pipeline OWASP Juice Shop

# Configuration globale
defaults:
  run:
    shell: bash
